# apps/users/serializers.py
"""
Serializers for Users API:
- RegisterSerializer: creates a user (email + password [+ optional username])
- UserPublicSerializer: safe public representation returned by the API
"""
from typing import Any

from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError as DjangoValidationError
from rest_framework import serializers

User = get_user_model()


class UserPublicSerializer(serializers.ModelSerializer):
    """
    Public user fields we can safely expose in API responses.
    """
    class Meta:
        model = User
        fields = ("id", "email", "first_name", "last_name", "is_staff")
        read_only_fields = fields
        extra_kwargs = {
            "email": {"help_text": "User e-mail"},
            "first_name": {"help_text": "First name"},
            "last_name": {"help_text": "Last name"},
            "is_staff": {"help_text": "Admin/staff flag"},
        }


class RegisterSerializer(serializers.ModelSerializer):
    """
    Payload for user registration.

    Required:
      - email
      - password

    Optional:
      - username (autogenerated from email if omitted)
    """
    password = serializers.CharField(
        write_only=True,
        min_length=8,
        help_text="Password (min 8 chars). Validated by Django password validators.",
    )
    username = serializers.CharField(
        required=False,
        allow_blank=True,
        help_text="If empty, will be generated from the e-mail local part.",
    )

    class Meta:
        model = User
        fields = ("email", "password", "username")
        extra_kwargs = {
            "email": {"help_text": "Unique e-mail used for login"},
        }

    # -------- field-level validators --------

    def validate_email(self, value: str) -> str:
        """
        Normalize to lowercase and ensure uniqueness (case-insensitive).
        """
        value = (value or "").strip().lower()
        if not value:
            raise serializers.ValidationError("Email is required.")
        if User.objects.filter(email__iexact=value).exists():
            raise serializers.ValidationError("User with this email already exists.")
        return value

    def validate_password(self, value: str) -> str:
        """
        Run Django's password validators to keep policy consistent with the project.
        """
        try:
            validate_password(value)
        except DjangoValidationError as exc:
            raise serializers.ValidationError(list(exc.messages))
        return value

    # -------- object creation --------

    def create(self, validated_data: dict[str, Any]) -> User:
        """
        Create the user using the project's user model.
        Username is generated from email if not provided or blank.
        """
        email: str = validated_data["email"].strip().lower()
        raw_password: str = validated_data["password"]
        base = (validated_data.get("username") or email.split("@")[0]).strip().lower() or "user"

        # ensure username uniqueness
        username = base
        i = 1
        while User.objects.filter(username=username).exists():
            username = f"{base}{i}"
            i += 1

        user = User.objects.create_user(username=username, email=email, password=raw_password)
        return user
