# Generated by Django 5.2.7 on 2025-10-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
