# Generated by Django 5.2.7 on 2025-10-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
