# Generated by Django 5.2.7 on 2025-10-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_description_alter_listing_district'),
    ]

    operations = [
    ]
