# Generated by Django 5.2.7 on 2025-10-28 09:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_booking_check_in_time_and_more'),
        ('listings', '0006_listing_listings_li_city_e45c53_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_end_after_start',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_listing_d217dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_listing_e73481_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'start_date', 'end_date', 'status'], name='bookings_bo_listing_e9078a_idx'),
        ),
    ]
