# Generated by Django 5.2.7 on 2025-10-28 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_listings_li_city_e45c53_idx_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['listing', 'author'], name='reviews_rev_listing_ff44fa_idx'),
        ),
    ]
